service: component-crafter-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 1024
  timeout: 25 # Reduced slightly to account for API Gateway limits
  environment:
    STAGE: dev
  # Using httpApi with explicit CORS
  httpApi:
    cors:
      allowedOrigins:
        - 'https://acciojob-assessment-frontend.vercel.app'
        - 'http://localhost:3000'
      allowedMethods:
        - '*'
      allowedHeaders:
        - '*'
      allowCredentials: true

functions:
  app:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: './webpack.config.cjs'
    includeModules: true
    packager: 'npm'

package:
  exclude:
    - .env
    - .gitignore
    - README.md
    - node_modules/**
    - test/**
    - .serverless/**
  include:
    - src/**
    - node_modules/**

# Removed the problematic GatewayResponse resource